### PR TITLE
Travis CI -> GitHub Actions

### PR DESCRIPTION
**Pull request by petrparolek**

### CODE REVIEW

**Comment by foxycode** [comment]
@petrparolek Why fix deprecated packages?

**Comment by petrparolek** [comment]
@foxycode ask @f3l1x

**Comment by f3l1x** [comment]
It's about quality of our work. I hope you're enjoying that kind of support @foxycode. It's a privilege, right?

**Comment by foxycode** [comment]
Ok then, thanks guys :)

**Pull request merged**
